### ISSUE TITLE
Publish in Chef supermarket

### ISSUE THREAD

**Issue by ghost** [wanelo-chef/pkg_add#1]
Hi,

I have put your cookbook into Chef supermarket (https://supermarket.chef.io/cookbooks/pkg_add). This means I am currently the owner. If you want to contact me to transfer it to you, don't hesitate, call me

Vincent

**Comment by sax** [comment]
Would you mind transferring ownership to sax in supermarket?

**Comment by ghost** [comment]
Done !

**Comment by sax** [comment]
Thank you!

On Tue, Aug 4, 2015 at 10:37 PM, vvanholl notifications@github.com wrote:

> Closed #1 https://github.com/wanelo-chef/pkg_add/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wanelo-chef/pkg_add/issues/1#event-373816175.

## 

---

e s
